Cleanup
bbmokhtari/django-translations pull request #78
Opened 2021-06-15 21:38 UTC by hramezani

# Pull requests

Thank you for submitting a contribution to Django Translations.

Please ensure the following steps have been taken:

## All changes

- [ ] Is this contribution for a known issue in the issues? If so mention it.
- [ ] Is there a task for this contribution in the project board? If so mention it.

## Code changes

- [ ] Have you run the unit tests on the project before submitting the contribution?
- [ ] Have you added the appropriate unit tests for your contribution to the project?
- [ ] Have you added the appropriate documentation for your contribution to the project?
- [ ] Have you styled your code properly based on the contribution guidelines?

## Documentation changes

- [ ] Have you built the documentation?
- [ ] Have you run the documentation tests?

## Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

2021-06-17 07:41 UTC, bbmokhtari commented
Thank you for putting in the time to create a pull request for Django-Translations.
All in all it's OK, but I think it needs some very minor changes.

2021-06-17 07:48 UTC, bbmokhtari requested changes
Please check the PR code comments.
Also feel free to discuss any of them with me if you have another opinion.

2021-06-17 07:48 UTC, bbmokhtari commented on .github/README.md
> +  [solution](https://docs.djangoproject.com/en/3.1/topics/i18n/translation/)
I this this should remain the lowest possible version to ensure backwards-compatibility.
So `2.2` for now.

2021-06-17 07:48 UTC, bbmokhtari commented on .travis.yml
> -    - name: "Python 3.6, Django 2.1, SQLite - Doc Test"
The test for "Python 3.6, Django 2.0, SQLite - Doc Test" should also be removed. (`stage` should remain as you know)

2021-06-17 07:48 UTC, bbmokhtari commented on .travis.yml
> -    - name: "Python 3.8, Django 2.1, SQLite - Doc Test"
The test for "Python 3.8, Django 2.0, SQLite - Doc Test" should also be removed.

2021-06-17 07:48 UTC, bbmokhtari commented on .travis.yml
> +        - pip install django~=3.0
Please allow this to remain the lowest possible version for ensuring the backwards-compatibility issue mentioned above, meaning `2.2`.

2021-06-17 07:48 UTC, bbmokhtari commented on requirements_dev.txt
> +Django~=3.0
Please allow this to remain the lowest possible version for ensuring the backwards-compatibility issue mentioned above, meaning `2.2`.

2021-06-17 08:07 UTC, hramezani commented
Thanks @bbmokhtari for the review. I've addressed all your comments.

2021-06-18 07:31 UTC, bbmokhtari approved these changes

2021-06-18 07:32 UTC, merged

2021-06-18 07:33 UTC, bbmokhtari commented
Approved and merged. Thank you.